replicaCount: 1

containerPorts:
  - name: http
    containerPort: 80
    protocol: "TCP"

service:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 80
      protocol: "TCP"
      port: 8080


livenessProbe:
  enabled: false

readinessProbe:
  enabled: false


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-send-timeout: '150'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '150'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '120'
    nginx.ingress.kubernetes.io/proxy-body-size: '100m'
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: '128k'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '32'
  hosts:
    - name: trademap.khc.kz
      path: /
      port: 80